#pragma once

#include "juce_audio_processors/juce_audio_processors.h"
#include "juce_audio_formats/juce_audio_formats.h"

// Must include the BinaryData header now to load the sounds.  This was generated by our CMakeLists.
// If you add different sounds to your Binary Data you'll need to rerun CMake to update the header.
#include <BinaryData.h>

class SamplerAudioProcessor final : public juce::AudioProcessor
{
public:
    SamplerAudioProcessor();

    bool hasEditor() const override { return true; }
    const juce::String getName() const override { return JucePlugin_Name; }
    bool acceptsMidi() const override { return true; }
    bool producesMidi() const override { return false; }
    bool isMidiEffect() const override { return false; }
    double getTailLengthSeconds() const override { return 0.0; }
    int getNumPrograms() override { return 1; }
    int getCurrentProgram() override { return 0; }
    void setCurrentProgram(int) override { }
    const juce::String getProgramName(int) override { return {}; }
    void changeProgramName(int, const juce::String&) override { }

    bool isBusesLayoutSupported(const BusesLayout& layouts) const override;
    void prepareToPlay(double sampleRate, int samplesPerBlock) override;
    void releaseResources() override { }
    void processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) override;
    void getStateInformation(juce::MemoryBlock& destData) override;
    void setStateInformation(const void* data, int sizeInBytes) override;
    juce::AudioProcessorEditor* createEditor() override;

    juce::AudioProcessorValueTreeState apvts;

private:
    static juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();
    void clearUnusedOutputChannels(juce::AudioBuffer<float>& buffer) const;

    juce::Synthesiser synth;
    static constexpr auto numVoices = 8;

    /* 1. The AudioFormatManager adds the ability to handle different types of audio formats, such as WAV and AIFF
     * AudioFormatManager Class: https://docs.juce.com/master/classjuce_1_1AudioFormatManager.html */

    juce::AudioFormatManager formatManager;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(SamplerAudioProcessor)
};
